### ISSUE TITLE
Wonderful work!

### ISSUE THREAD

**Issue by zhangfq-chemistry** [unclejimbo/Klein#1]
Would you like to provide one example of selection and removing?

**Comment by unclejimbo** [comment]
Hi. What do mean by selection and removing?

**Comment by zhangfq-chemistry** [comment]
I want to pick one object and edit (for example, pick one of the many spheres in instancing-example and remove it). Thanks a lot for you useful work!

**Comment by unclejimbo** [comment]
Well, it depends on how you represent your objects.

If you use one `QEntity` for each object, then you could use `QObjectPicker` to pick. The `QEntity` can be detached from the scene tree by `setParent(nullptr)`.

In the instancing case, the spheres are represented by a single entity, so you should manage the picking removing by yourself. You can get the picked 3d position from qt, so you know which instance is picked, and update the instance buffer.

**Comment by zhangfq-chemistry** [comment]
Thanks! I worry about the memory-leak if one QEntity is detached simply from parent. Because there is not a delete() or destroy() I can find inside the Class. Can you give me your email, telephone, or QQ? I have several questions to ask. Thank ShaoDong! I am Zhang Fu-Qiang, a teacher from Shanxi Normal University.

**Comment by zhangfq-chemistry** [comment]
Thanks! I worry about the memory-leak if one QEntity is detached simply from parent.  Can you give me your email, telephone, or QQ? I have several questions to ask. Thank ShaoDong!

**Comment by zhangfq-chemistry** [comment]
Thanks! I worry about the memory-leak if one QEntity is detached simply from parent. Because there is not a delete() or destroy() I can find inside the Class. Can you give me your email, telephone, or QQ? I have several questions to ask. Thank ShaoDong! I am Zhang Fu-Qiang, a teacher from Shanxi Normal University.

**Comment by unclejimbo** [comment]
You can contact me through my email, it's on my profile page.
